/*

  API Inventory
 *
 * This is the Challenge API
 *
 * API version: 1.0.0
 * Contact: maxmonte.vix@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
*/
//package swagger
package main

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/Desafio/1.0.0/",
		Index,
	},

	/*********************************************************************************************************************************************
	 *       API  Routes
	 *
	 ***********************************************************************************************************************************************
	 */
	Route{
		"ProjectApiApinamePost",
		strings.ToUpper("Post"),
		"/Desafio/1.0.0/project/{projectname}/{apiname}",
		ProjectApiApinamePost,
	},
	Route{
		"ProjectApiApinameDelete",
		strings.ToUpper("Delete"),
		"/Desafio/1.0.0/project/{projectname}/{apiname}",
		ProjectApiApinameDelete,
	},

	Route{
		"ProjectApiApinameGet",
		strings.ToUpper("Get"),
		"/Desafio/1.0.0/project/{projectname}/{apiname}",
		ProjectApiApinameGet,
	},

	Route{
		"ProjectApiApinamePut",
		strings.ToUpper("Put"),
		"/Desafio/1.0.0/project/{projectname}/{apiname}",
		ProjectApiApinamePut,
	},

	/*********************************************************************************************************************************************
	 *       Project  Routes
	 *
	 ***********************************************************************************************************************************************
	 */

	Route{
		"SearchProjects",
		strings.ToUpper("Get"),
		"/Desafio/1.0.0/project/",
		SearchProjects,
	},
	Route{
		"AddProject",
		strings.ToUpper("Post"),
		"/Desafio/1.0.0/project/",
		AddProject,
	},

	Route{
		"ProjectProjectnameDelete",
		strings.ToUpper("Delete"),
		"/Desafio/1.0.0/project/{projectname}",
		ProjectProjectnameDelete,
	},

	Route{
		"ProjectProjectnameGet",
		strings.ToUpper("Get"),
		"/Desafio/1.0.0/project/{projectname}",
		ProjectProjectnameGet,
	},

	Route{
		"ProjectProjectnamePut",
		strings.ToUpper("Put"),
		"/Desafio/1.0.0/project/{projectname}",
		ProjectProjectnamePut,
	},
}
